### Test Login Endpoint
POST http://localhost:5000/api/v2/auth/login
Content-Type: application/json

{
    "email": "laramestdagh2002@gmail.com",
    "password": "password_dnd_co"
}

###

### Test Refresh Token Endpoint
POST http://localhost:5000/api/v2/auth/refresh
Content-Type: application/json

{
    "refreshToken": "JrLgP6tNsoC4w86UB7kSCX0RXDsfNqIsT4LT6sFnzbw",
    "userId": "testUserId"
}

###

### Test Secured Endpoint with JWT Token (Example Endpoint)
GET http://localhost:5000/api/v2/player-characters
Authorization: Bearer your_jwt_token_here






### Get All Player Characters
GET http://localhost:5000/api/v2/player-characters HTTP/1.1
Content-Type: application/json

###

### Get Player Character by ID
GET http://localhost:5000/api/v2/player-characters/1 HTTP/1.1
Content-Type: application/json

###

### Create a New Player Character
POST http://localhost:5000/api/v2/player-characters HTTP/1.1
Content-Type: application/json

{
    "playerName": "John",
    "name": "Arthas",
    "race": "Human",
    "imagePath": null,
    "strength": 16,
    "dexterity": 14,
    "constitution": 14,
    "intelligence": 12,
    "wisdom": 10,
    "charisma": 16,
    "currentHP": 35,
    "maxHP": 40,
    "tempHP": 0,
    "armorClass": 16,
    "walkingSpeed": 30,
    "flyingSpeed": null,
    "swimmingSpeed": null,
    "darkvisionRange": null,
    "isAlive": true,
    "knownLanguages": [],
    "resistances": ["Bludgeoning", "Cold"],
    "weaknesses": ["Fire", "Lightning"],
    "hasOver20Stats": false
}


###

### Update an Existing Player Character
PUT http://localhost:5000/api/v2/player-characters/1 HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "playerName": "John",
    "name": "Arthas",
    "race": "Human",
    "imagePath": null,
    "strength": 17,
    "dexterity": 14,
    "constitution": 14,
    "intelligence": 12,
    "wisdom": 10,
    "charisma": 16,
    "currentHP": 21,
    "maxHP": 40,
    "tempHP": 0,
    "armorClass": 16,
    "walkingSpeed": 30,
    "flyingSpeed": null,
    "swimmingSpeed": null,
    "darkvisionRange": null,
    "isAlive": true,
    "knownLanguages": [],
    "resistances": ["Bludgeoning", "Cold"],
    "weaknesses": ["Fire", "Lightning"],
    "hasOver20Stats": false
}

###

### Soft Delete a Player Character
DELETE http://localhost:5000/api/v2/player-characters/1 HTTP/1.1
Content-Type: application/json

###

### Get All DM Characters
GET http://localhost:5000/api/v2/dm-characters HTTP/1.1
Content-Type: application/json

###

### Get DM Character by ID
GET http://localhost:5000/api/v2/dm-characters/1 HTTP/1.1
Content-Type: application/json

###

### Create a New DM Character
POST http://localhost:5000/api/v2/dm-characters HTTP/1.1
Content-Type: application/json

{
    "playerName": "DungeonMaster1",
    "name": "Zugthrok the Mighty",
    "race": "Orc",
    "strength": 18,
    "dexterity": 14,
    "constitution": 16,
    "intelligence": 8,
    "wisdom": 10,
    "charisma": 12,
    "currentHP": 100,
    "maxHP": 100,
    "tempHP": 0,
    "armorClass": 17,
    "walkingSpeed": 30,
    "flyingSpeed": null,
    "swimmingSpeed": null,
    "darkvisionRange": null,
    "legendaryActions": "Legendary Slash, Intimidating Roar",
    "specialAbilities": "Darkvision, Fury of Blows",
    "isAlive": true,
    "knownLanguages": ["Common", "Orc"],
    "resistances": ["Bludgeoning", "Poison"],
    "weaknesses": ["Psychic", "Fire"],
    "hasOver20Stats": false
}

###

### Update an Existing DM Character
PUT http://localhost:5000/api/v2/dm-characters/1 HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "Zugthrok the Mighty",
    "race": "Half-Orc",
    "strength": 18,
    "dexterity": 14,
    "constitution": 16,
    "intelligence": 8,
    "wisdom": 10,
    "charisma": 12,
    "currentHP": 100,
    "maxHP": 100,
    "tempHP": 0,
    "armorClass": 17,
    "walkingSpeed": 30,
    "flyingSpeed": null,
    "swimmingSpeed": null,
    "darkvisionRange": null,
    "legendaryActions": "Legendary Slash, Intimidating Roar",
    "specialAbilities": "Darkvision, Fury of Blows",
    "isAlive": true,
    "knownLanguages": ["Common", "Orc"],
    "resistances": ["Bludgeoning", "Poison"],
    "weaknesses": ["Psychic", "Fire"],
    "hasOver20Stats": false
}

###

### Soft Delete a DM Character
DELETE http://localhost:5000/api/v2/dm-characters/1 HTTP/1.1
Content-Type: application/json

###
